import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useDispatch, useSelector } from 'react-redux';
import { IconButton } from '../../components/IconButton';
import { RouteCard } from '../../components/RouteCard';
import { RootState } from '../../store/store';
import { setSearch } from '../../store/slices/routeSlice';
export default function Home() {
  const dispatch = useDispatch(); const { search, routes } = useSelector((state: RootState) => state.routes); const name = useSelector((state: RootState) => state.auth.name);
  const filtered = useMemo(() => routes.filter(route => `${route.name} ${route.from} ${route.to}`.toLowerCase().includes(search.toLowerCase())), [routes, search]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><View><Text style={styles.eyebrow}>SATURDAY, 23 AUGUST</Text><Text style={styles.greeting}>Good morning, {name.split(' ')[0]}</Text></View><IconButton name="notifications-outline" light /></View><View style={styles.searchBox}><Ionicons name="search" color="#71908A" size={20} /><TextInput value={search} onChangeText={value => dispatch(setSearch(value))} placeholder="Where are you going?" placeholderTextColor="#91A19C" style={styles.input} /><Ionicons name="options-outline" color="#E76F51" size={20} /></View><View style={styles.quickRow}><Pressable style={styles.quick} onPress={() => router.push('/tracking')}><View style={[styles.quickIcon, { backgroundColor: '#F9E6DF' }]}><Ionicons name="navigate" size={19} color="#D85D40" /></View><Text style={styles.quickText}>Live tracking</Text></Pressable><Pressable style={styles.quick} onPress={() => router.push('/scanner')}><View style={[styles.quickIcon, { backgroundColor: '#E4F1EC' }]}><Ionicons name="scan-outline" size={19} color="#27816F" /></View><Text style={styles.quickText}>Scan a ticket</Text></Pressable><Pressable style={styles.quick} onPress={() => router.push('/admin-dashboard')}><View style={[styles.quickIcon, { backgroundColor: '#F8EFD8' }]}><Ionicons name="pulse-outline" size={19} color="#B87925" /></View><Text style={styles.quickText}>Operations</Text></Pressable></View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Nearby routes</Text><Text style={styles.updated}>Updated just now</Text></View>{filtered.map(route => <RouteCard key={route.id} route={route} onPress={() => router.push({ pathname: '/tracking', params: { route: route.name } })} />)}{filtered.length === 0 && <Text style={styles.empty}>No routes match that search.</Text>}<View style={styles.notice}><Ionicons name="megaphone-outline" size={20} color="#B87925" /><View style={{ flex: 1 }}><Text style={styles.noticeTitle}>Service note</Text><Text style={styles.noticeBody}>Expect a 5 minute delay around Guadalupe from 2–4 PM.</Text></View><Ionicons name="chevron-forward" size={18} color="#9C8A60" /></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8F5EF' }, content: { padding: 22, paddingBottom: 32 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 }, eyebrow: { color: '#E76F51', fontSize: 10, letterSpacing: 1.3, fontWeight: '800' }, greeting: { color: '#163B3E', fontSize: 25, fontWeight: '800', marginTop: 6 }, searchBox: { backgroundColor: '#FFFDF9', borderColor: '#E0E9E2', borderWidth: 1, borderRadius: 15, height: 56, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 11 }, input: { flex: 1, color: '#163B3E', fontSize: 15 }, quickRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 24 }, quick: { alignItems: 'center', gap: 8, width: '31%' }, quickIcon: { width: 43, height: 43, borderRadius: 14, justifyContent: 'center', alignItems: 'center' }, quickText: { fontSize: 11, color: '#526B66', fontWeight: '700' }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 12 }, sectionTitle: { fontSize: 18, fontWeight: '800', color: '#163B3E' }, updated: { fontSize: 10, color: '#91A19C' }, empty: { textAlign: 'center', padding: 28, color: '#758782' }, notice: { marginTop: 12, backgroundColor: '#F7EED7', borderRadius: 14, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12 }, noticeTitle: { color: '#6D5529', fontWeight: '800', fontSize: 13 }, noticeBody: { color: '#8A7548', fontSize: 11, lineHeight: 17, marginTop: 3 } });
